sudo: false
language: python
install:
  - make
  - pip install coveralls
script:
  - make isort-check
  - make flake8
cache: pip
jobs:
  include:
    - stage: test
      python: 3.6
      script:
        - make coverage
after_success:
  - coveralls
