language: python
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOX_ENV=flake8
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOX_ENV=isort-check
      dist: xenial
      sudo: true
install:
  - pip install -U setuptools tox coveralls
script:
  - if [ $TOX_ENV == "isort-check" ];
    then make isort-check;
    else tox -e $TOX_ENV;
    fi
after_success:
  - |
    if [[ "$TOX_ENV" == "py37" ]] ; then make coverage && coveralls; fi
